frontend_seller:
  host: "127.0.0.1"   # VM1
  port: 8080

frontend_buyer:
  host: "127.0.0.1"      #VM2
  port: 8090

customer_db:
  host:  "127.0.0.1"        # VM3
  port: 50051           
  seller_port: 50053    

backend_product_db:
  host: "127.0.0.1"          # VM4
  port: 50052

soap:
  host: "127.0.0.1"       #can be on any VM     
  port: 8000